# Generated by Django 4.1.1 on 2022-10-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='liked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
