# Generated by Django 4.0 on 2022-09-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcheckout',
            name='address',
        ),
        migrations.RemoveField(
            model_name='productcheckout',
            name='payed',
        ),
    ]
