# Generated by Django 4.0 on 2022-09-15 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('cart', '0003_remove_cart_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('checkout', '0002_remove_productcheckout_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed', models.BooleanField(default=False)),
                ('delivery_status', models.CharField(choices=[('processing', 'Processing'), ('packed', 'Packed'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered')], default='processing', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='address.address')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.user')),
                ('cart', models.ManyToManyField(to='cart.Cart')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductCheckout',
        ),
    ]
