# Generated by Django 4.0 on 2022-09-16 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_cartcheckout_delete_productcheckout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartcheckout',
            name='address',
        ),
    ]
