# Generated by Django 4.0 on 2022-09-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_cartcheckout_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartcheckout',
            name='checked_out',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cartcheckout',
            name='payed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
