# Generated by Django 4.0 on 2022-07-29 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image',
        ),
    ]
