# Generated by Django 4.0 on 2022-08-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0004_slider_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
