# Generated by Django 4.1 on 2023-05-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0005_alter_slider_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='count',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='description',
        ),
    ]
