# Generated by Django 4.0 on 2022-08-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
