# Generated by Django 4.0 on 2022-09-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('packed', 'Packed'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered')], default='processing', max_length=50),
        ),
    ]
