# Generated by Django 4.1 on 2023-04-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_image_product_image1_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
    ]
