# Generated by Django 4.1 on 2023-04-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_image1_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secondimage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
